# Generated by Django 3.0.5 on 2020-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_img',
            field=models.ImageField(blank=True, upload_to='vehicles/'),
        ),
    ]
