# Generated by Django 3.0.5 on 2020-10-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200414_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_img',
            new_name='img2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_no',
        ),
    ]
